services:

  app:
    build: .
    container_name: url-shortener-app

    env_file:
      - .env.docker

    ports:
      - "8000:8000"

    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17
    container_name: url-shortener-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shortener

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d url_shortener"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: